- name: Ensure terminator is installed
  package:
    name: "{{ zsh_terminator_package }}"
    state: present
  become: true
  become_user: root

- name: Create directories for config files (if applicable)
  file:
    path: "{{ item.dest_path | default(item.src_path) | default(item) | dirname }}"
    state: directory
    mode: "0755"
  when: |
    (item.dest_path | default(item.src_path) | default(item) | dirname) != ""
  loop: "{{ zsh_config_files | default([]) }}"

- name: Copy config files
  copy:
    src: "{{ item.src_path | default(item) }}"
    dest: "{{ item.dest_path | [ansible_user_dir, default(item.src_path | default(item))] | join('/') | realpath }}"
    mode: "{{ item.mode | default(zsh_config_file_default_mode) }}"
  loop: "{{ zsh_config_files | default([]) }}"

- name: Download fonts
  get_url:
    url: "{{ item.url }}"
    dest: "files/{{ item.src }}"
    mode: "0644"
  delegate_to: localhost
  when: url in item
  loop: "{{ fonts_user | default([]) }}"

- name: Install fonts
  include_role:
    name: ontic.fonts

- name: Cleanup downloaded fonts
  file:
    path: "files/{{ item.src }}"
    state: absent
  delegate_to: localhost
  when: url in item
  loop: "{{ fonts_user | default([]) }}"
